version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"
  npm-registry-registry-yarnpkg-com:
    type: npm-registry
    url: https://registry.yarnpkg.com
    token: "${{secrets.NPM_REGISTRY_REGISTRY_YARNPKG_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  labels:
  - dependabot
  versioning-strategy: increase
  ignore:
  - dependency-name: uglify-js
    versions:
    - 3.12.5
    - 3.12.6
    - 3.12.7
    - 3.12.8
    - 3.13.0
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: node-abi
    versions:
    - 2.19.3
    - 2.20.0
    - 2.21.0
  - dependency-name: string.prototype.trimend
    versions:
    - 1.0.3
  - dependency-name: resolve
    versions:
    - 1.19.0
  registries:
  - npm-registry-registry-npmjs-org
  - npm-registry-registry-yarnpkg-com
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  labels:
  - dependabot
  versioning-strategy: increase
